### Recuperar todas las scores
GET http://localhost:8080/scores

### Recuperar score por id
GET http://localhost:8080/scores/e93ca12f-983a-4e42-b7b1-02a82149858e

### Crear score
POST http://localhost:8080/scores
Content-Type: application/json

{
    "palabras_acertadas": 10,
    "palabras_totales": 20,
    "tiempo_segundos": 34.2,
    "precision_porcentaje": 50.3
}

### Actualizar score
PATCH http://localhost:8080/scores/e93ca12f-983a-4e42-b7b1-02a82149858e
Content-Type: application/json

{
    "precision_porcentaje": 88.88
}

### Borrar score
DELETE http://localhost:8080/scores/a9e52f5d-829b-49cc-91d1-31752dc819f5
